repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-file
          - tools/LICENSE_HEADER.txt
          - --comment-style
          - "#"
